global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "dicey-backend"
    static_configs:
      - targets: ["backend:8080"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
